import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import  Header  from "@/components/Header.jsx";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";

const inter=Inter({ subsets: ["latin"] });
export const metadata = {
  title: "CareerForge AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <ClerkProvider appearance={{baseTheme:dark}} >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header/>

            <main className="min-h-screen"> {children} </main>
            <Toaster richColors />
            <footer className=" bg-black py-12">
              <div className="container mx-auto text-center text-gray-200">
                Made by Gunjan Jain
              </div>
            </footer>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
